language: shell
jobs:
  include:
  - stage: build-linux
    dist: focal
    before_install:
    - sudo apt-get -qq update
    - sudo apt-get -y dist-upgrade
    - sudo apt-get -y install awscli build-essential qt5-default libqt5websockets5-dev
    script:
    - mkdir build
    - cd build
    - qmake ..
    - make
  - stage: build-windows
    os: windows
    before_install:
    - "[[ ! -f C:/tools/msys64/msys2_shell.cmd ]] && rm -rf C:/tools/msys64"
    - choco uninstall -y mingw
    - choco upgrade --no-progress -y msys2
    - export msys2='cmd //C RefreshEnv.cmd '
    - export msys2+='& set MSYS=winsymlinks:nativestrict '
    - export msys2+='& C:\\tools\\msys64\\msys2_shell.cmd -defterm -no-start'
    - export mingw64="$msys2 -mingw64 -full-path -here -c "\"\$@"\" --"
    - export msys2+=" -msys2 -c "\"\$@"\" --"
    - $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-toolchain
    - $msys2 pacman -Syu --noconfirm
    - $msys2 pacman -S --needed --noconfirm make mingw-w64-x86_64-qt5
    - export PATH=/C/tools/msys64/mingw64/bin:$PATH
    script:
    - mkdir build
    - cd build
    - $mingw64 qmake ..
    - $mingw64 make
