name: Build project

on: push

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Update and install packages
        run: |
          sudo apt-get -qq update
          sudo apt-get -y install build-essential qt5-default libqt5websockets5-dev
      - name: Run build script
        run: |
          mkdir build
          cd build
          qmake ..
          make
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            make
            mingw-w64-x86_64-qt5
            mingw-w64-x86_64-gcc
      - name: Run build script
        run: |
          mkdir build
          cd build
          msys2 -c 'qmake ..'
          msys2 -c 'make'
